name: Report Coverage
on:
  push:
    branches:
    - master
    paths:
    - 'abalone/*'
jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - uses: dschep/install-pipenv-action@v1
    - run: pipenv install --dev
    - run: pipenv run coverage run
    - run: pipenv run coverage xml
    - uses: codecov/codecov-action@v1
      with:
        flags: unittest
